train:
  _target_: src.datasets.LibrispeechDataset
  part: "test-clean"
  max_audio_length: 20.0
  max_text_length: 200
  limit: 16
  instance_transforms: ${transforms.instance_transforms.train}
val:
  _target_: src.datasets.LibrispeechDataset
  part: "test-clean"
  max_audio_length: 20.0
  max_text_length: 200
  limit: 16
  instance_transforms: ${transforms.instance_transforms.inference}
