defaults:
  - model: conformer
  - metrics: example
  - datasets: custom_dir
  - dataloader: example
  - transforms: asr
  - _self_

text_encoder:
  _target_: src.text_encoder.CTCTextEncoder
  beam_size: 10
  kenlm_model_path: saved/3-gram.arpa
  alpha: 1
  beta: 0.5

inferencer:
  device_tensors: ["spectrogram", "text_encoded"]
  device: auto
  save_path: "custom_dataset/preds"
  seed: 1
  from_pretrained: null

custom_dataset:
  dataset_root: null
  audio_dir: ${custom_dataset.dataset_root}/audio
  transcription_dir: ${custom_dataset.dataset_root}/transcriptions
