defaults:
  - model: conformer
  - metrics: example
  - datasets: librispeech_eval_test_other
  - dataloader: example
  - transforms: example_only_instance
  - _self_
text_encoder:
  _target_: src.text_encoder.CTCTextEncoder
inferencer:
  device_tensors: ["spectrogram", "text_encoded"]
  device: auto
  save_path: "librispeech/test-other"
  seed: 1
  from_pretrained: "saved/testing/model_best.pth"
  beam_size: 10
