defaults:
  - model: conformer
  - metrics: example
  - datasets: librispeech_eval_test_other
  - dataloader: example
  - transforms: asr
  - _self_
text_encoder:
  _target_: src.text_encoder.CTCTextEncoder
  beam_size: 5
  kenlm_model_path: null
inferencer:
  device_tensors: ["spectrogram", "text_encoded"]
  device: auto
  save_path: "librispeech/test-other"
  seed: 1
  from_pretrained: null
  beam_size: 10
