defaults:
  - model: conformer
  - metrics: example
  - datasets: librispeech_eval_test_clean
  - dataloader: example
  - transforms: asr
  - _self_
text_encoder:
  _target_: src.text_encoder.CTCTextEncoder
  beam_size: 5
  kenlm_model_path: saved/3-gram.arpa
  alpha: 0.5
  beta: 1.5
inferencer:
  device_tensors: ["spectrogram", "text_encoded"]
  device: auto
  save_path: "librispeech/test-clean"
  seed: 1
  from_pretrained: null
  beam_size: 10
