defaults:
  - model: conformer
  - writer: cometml
  - metrics: example
  - datasets: librispeech_train
  - dataloader: example
  - transforms: asr
  - _self_
optimizer:
  _target_: torch.optim.AdamW
  lr: 3e-4
  betas: [0.9, 0.98]
  eps: 1e-8
  weight_decay: 1e-2
lr_scheduler:
  _target_: torch.optim.lr_scheduler.OneCycleLR
  max_lr: 1e-3
  pct_start: 0.1
  steps_per_epoch: ${trainer.epoch_len}
  epochs: ${trainer.n_epochs}
  anneal_strategy: cos
loss_function:
  _target_: src.loss.CTCLossWrapper
text_encoder:
  _target_: src.text_encoder.CTCTextEncoder
  beam_size: 5
  kenlm_model_path: null
trainer:
  log_step: 100
  n_epochs: 10
  epoch_len: null
  device_tensors: ["spectrogram", "text_encoded"]
  resume_from: null
  device: cuda
  override: True
  monitor: "min val_WER_(Argmax)"
  save_period: 1
  early_stop: 5
  save_dir: "saved"
  seed: 1
  beam_size: 3
  use_amp: true
  amp_dtype: bf16
